openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloWorldDto"
  /auth/sign-up:
    post:
      operationId: AuthController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpBodyDto"
      responses:
        "201":
          description: ""
      tags:
        - auth
  /auth/sign-in:
    post:
      operationId: AuthController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInBodyDto"
      responses:
        "200":
          description: ""
      tags:
        - auth
  /auth/sign-out:
    post:
      operationId: AuthController_signOut
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - auth
  /auth/session:
    get:
      operationId: AuthController_getSessionInfo
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSessionInfoDto"
      tags:
        - auth
  /account:
    get:
      operationId: AccountController_getAccount
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDto"
      tags:
        - account
    patch:
      operationId: AccountController_patchAccount
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchAccountDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDto"
      tags:
        - account
  /block-list/items:
    get:
      operationId: BlockListController_getList
      summary: Retrieve block list for a user
      parameters:
        - name: q
          required: false
          in: query
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlockListDto"
      tags:
        - block-list/items
    post:
      operationId: BlockListController_addBlockItem
      summary: Add a new block item
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddBlockItemDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlockItemDto"
      tags:
        - block-list/items
  /block-list/items/{id}:
    put:
      operationId: BlockListController_updateBlockItem
      summary: Update an existing block item
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBlockItemDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlockItemDto"
      tags:
        - block-list/items
    delete:
      operationId: BlockListController_removeBlockItem
      summary: Remove a block item
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlockItemDto"
      tags:
        - block-list/items
info:
  title: Easy Block API
  description: ""
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    HelloWorldDto:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    SignUpBodyDto:
      type: object
      properties:
        email:
          type: string
          example: test@gmail.com
        password:
          type: string
          example: password
      required:
        - email
        - password
    SignInBodyDto:
      type: object
      properties:
        email:
          type: string
          example: test@gmail.com
        password:
          type: string
          example: password
      required:
        - email
        - password
    GetSessionInfoDto:
      type: object
      properties:
        id:
          type: number
        email:
          type: string
          example: test@gmail.com
        iat:
          type: number
        exp:
          type: number
      required:
        - id
        - email
        - iat
        - exp
    AccountDto:
      type: object
      properties:
        id:
          type: number
        ownerId:
          type: number
        isBlockingEnabled:
          type: boolean
      required:
        - id
        - ownerId
        - isBlockingEnabled
    PatchAccountDto:
      type: object
      properties:
        isBlockingEnabled:
          type: boolean
    BlockItemDto:
      type: object
      properties:
        id:
          type: number
        blockListId:
          type: number
        type:
          type: string
          enum:
            - KeyWord
            - Website
        data:
          type: string
        createdAt:
          format: date-time
          type: string
      required:
        - id
        - blockListId
        - type
        - data
        - createdAt
    BlockListDto:
      type: object
      properties:
        id:
          type: number
        ownerId:
          type: number
        items:
          type: array
          items:
            $ref: "#/components/schemas/BlockItemDto"
      required:
        - id
        - ownerId
        - items
    AddBlockItemDto:
      type: object
      properties:
        type:
          type: string
          enum:
            - KeyWord
            - Website
        data:
          type: string
      required:
        - type
        - data
    UpdateBlockItemDto:
      type: object
      properties:
        type:
          type: string
          enum:
            - KeyWord
            - Website
          description: Type of the block item
        data:
          type: string
          description: Data associated with the block item, such as a keyword or URL
      required:
        - type
